### ISSUE TITLE
Failed to update ref: HttpError: Reference does not exist

### ISSUE THREAD

**Issue by hannesa2** [zofrex/mirror-branch#5]
My fork https://github.com/hannesa2/tensorflow/runs/1462290207?check_suite_focus=true

runs with this action into 

<img width="593" alt="image" src="https://user-images.githubusercontent.com/3314607/100419452-dd353480-3084-11eb-8950-463cdbecb217.png">

No clue what's wrong here. Do you have an idea ?

**Comment by zofrex** [comment]
I think the issue is that your fork does not have a 'nightly' branch. Could you try creating one and see if that resolves the issue?

That error message is not helpful, though. I'll see if that can be improved.

**Comment by hannesa2** [comment]
Indeed the `nightly` was missing.
May I suggest to add an option (or automatic) to create branch, when it's missing ?
